title: Root
description: If you die, I die too.
google_analytics: G-92WV8K2RTR
theme: jekyll-theme-cayman
show_urls: true
github:
  root_url: https://www.imdb.com/title/tt1839578/characters/nm0009918
  shaw_url: https://www.imdb.com/title/tt1839578/characters/nm1083404
  description: You can't live with me<br>I can't live without you<br>So if you die<br>I die too
